//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace T4EF.Models.POCO
{
    public partial class MovieReviewEntities : ObjectContext
    {
        public const string ConnectionString = "name=MovieReviewEntities";
        public const string ContainerName = "MovieReviewEntities";
    
        #region Constructors
    
        public MovieReviewEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public MovieReviewEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public MovieReviewEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Movie> Movies
        {
            get { return _movies  ?? (_movies = CreateObjectSet<Movie>("Movies")); }
        }
        private ObjectSet<Movie> _movies;
    
        public ObjectSet<Review> Reviews
        {
            get { return _reviews  ?? (_reviews = CreateObjectSet<Review>("Reviews")); }
        }
        private ObjectSet<Review> _reviews;

        #endregion
    }
}
