//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace T4EF.Models.POCO
{
    public partial class Review
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual int MovieID
        {
            get { return _movieID; }
            set
            {
                if (_movieID != value)
                {
                    if (Movie != null && Movie.ID != value)
                    {
                        Movie = null;
                    }
                    _movieID = value;
                }
            }
        }
        private int _movieID;
    
        public virtual string Summary
        {
            get;
            set;
        }
    
        public virtual int Ratin
        {
            get;
            set;
        }
    
        public virtual string Body
        {
            get;
            set;
        }
    
        public virtual string Reviewer
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Movie Movie
        {
            get { return _movie; }
            set
            {
                if (!ReferenceEquals(_movie, value))
                {
                    var previousValue = _movie;
                    _movie = value;
                    FixupMovie(previousValue);
                }
            }
        }
        private Movie _movie;

        #endregion
        #region Association Fixup
    
        private void FixupMovie(Movie previousValue)
        {
            if (previousValue != null && previousValue.Reviews.Contains(this))
            {
                previousValue.Reviews.Remove(this);
            }
    
            if (Movie != null)
            {
                if (!Movie.Reviews.Contains(this))
                {
                    Movie.Reviews.Add(this);
                }
                if (MovieID != Movie.ID)
                {
                    MovieID = Movie.ID;
                }
            }
        }

        #endregion
    }
}
